version: 2
updates:
  # Updates for root level package.json
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      dev-dependencies-root:
        dependency-type: 'development'

  # Updates for the eslint-config package
  - package-ecosystem: 'npm'
    directory: '/packages/eslint-config'
    schedule:
      interval: 'weekly'
    groups:
      dependencies-eslint-config:
        dependency-type: 'production'
